draft version

diff --git a/init/entrypoint b/init/entrypoint
--- a/init/entrypoint
+++ b/init/entrypoint
@@ -24,6 +24,9 @@ function validate(){
 ##############################################################################
 # write config vars with configfile template
 ##############################################################################
+function checkDatabase(){
+    mysql -u $DB_USER --password=$DB_PASS -h $DB_HOST -e "show tables" --database $DB_DATABASE
+}
 function writeConfigOptions(){
     echo "write config options"
     export DB_USERPROFILES=$DB_USERPROFILES
@@ -38,11 +41,21 @@ function writeConfigOptions(){
     export LANGUAGE=$LANGUAGE
     export TIMEZONE=$TIMEZONE
     export SUPERUSERS=$SUPERUSERS
-    cat /etc/sogo/sogo.conf.tmpl \
+    cat /opt/docker-config/sogo.conf.tmpl \
         | envsubst > /etc/sogo/sogo.conf
+
+    cat /etc/sogo/sogo.conf
+
+    cat /opt/docker-config/nginx.conf.tmpl \
+        > /etc/nginx/sites-enabled/default   
 }
 function init(){
     ## pre-config initialization
+    retry 10 5 "cannot connect to database." checkDatabase
+    if [[ $? != 0 ]]; then
+        echo "cannot initialize db: waitForDatabase" >&2
+        return 1
+    fi
 
     # write file based config options
     writeConfigOptions
@@ -51,13 +64,32 @@ function init(){
 }
 
 ##############################################################################
-function function_service(){
-    # whatever blocking call
-    tail -f /dev/null
+function service_sogo(){
+    NAME=sogo
+    USER=$NAME
+
+    PREFORK=3
+    PIDFILE=/var/run/$NAME/$NAME.pid
+    LOGFILE=/var/log/$NAME/$NAME.log
+
+    DAEMON=/usr/sbin/sogod
+    DAEMON_OPTS="-WONoDetach YES -WOWorkersCount $PREFORK -WOPidFile $PIDFILE -WOLogFile $LOGFILE"
+
+    install -o $USER -g $USER -m 755 -d /var/run/$NAME
+    install -o $USER -g $USER -m 750 -d /var/spool/$NAME
+    install -o $USER -g $USER -m 750 -d /var/log/$NAME
+
+    su -s /bin/bash -c "$DAEMON $DAEMON_OPTS" $USER
+}
+function service_nginx(){
+    nginx -g 'daemon off;'
+}
+function service_logs(){
+    tail -f /var/log/sogo/sogo.log /var/log/nginx/*
 }
 function start(){
     echo "starting applications..."
-    bgo service1 service2 function_service
+    bgo service_sogo service_nginx service_logs
     if [[ $? != 0 ]]; then
         echo "start failed. exiting now." >&2
         exit 1
